#!/bin/bash

df="\e[39m"
wh="\e[97m"
lrd="\e[91m"
lgn="\e[92m"
lyw="\e[93m"

function banner() {

    echo -e "    KtotoServer"
    echo -e "    Version    : 1.0"
    echo -e "    Type       : Check\n"

}

function status() {

    function index() {

        local URL="http://localhost:8080"
        local iProtocol=`curl -I $URL 2> /dev/null | sed -n 1p | awk '{print $1}'`
        local iStatus=`curl -I $URL 2> /dev/null | sed -n 1p | awk '{print $2}'`
        local iServer=`curl -I $URL 2> /dev/null | sed -n 3p | awk '{print $2" "$3}'`
        local iContent=`curl -I $URL 2> /dev/null | grep Content-Type: | awk '{print $2" "$3}'`

        echo -e "\n⚙️ Info Web Server Apache (index)"
        echo -e "   {"
        echo -e "     $wh Location$df     : $URL"
        echo -e "     $wh Protocol$df     : $iProtocol"
        if [[ "$iStatus" == "200" ]]; then
            echo -e "     $wh Status$df       : $lgn$iStatus OK$df"
        else
            newI=`curl -I $URL 2> /dev/null | sed -n 1p | awk '{print $2" "$3}'`
            echo -e "     $wh Status$df       : $lrd$newI$df"
        fi
        echo -e "     $wh Server$df       : $iServer"
        echo -e "     $wh Content-Type$df : $iContent"
        echo -e "   }\n"

    }

    function myAdmin() {

        local URL="http://localhost:8080/phpmyadmin"
        local iProtocol=`curl -I $URL 2> /dev/null | sed -n 1p | awk '{print $1}'`
        local iStatus=`curl -I $URL 2> /dev/null | sed -n 1p | awk '{print $2}'`
        local iServer=`curl -I $URL 2> /dev/null | sed -n 3p | awk '{print $2" "$3}'`
        local iContent=`curl -I $URL 2> /dev/null | grep Content-Type: | awk '{print $2" "$3}'`

        echo -e "⚙️ Info phpMyAdmin"
        echo -e "   {"
        echo -e "     $wh Location$df     : $URL"
        echo -e "     $wh Protocol$df     : $iProtocol"
        if [[ "$iStatus" == "200" ]]; then
            echo -e "     $wh Status$df       : $lgn$iStatus OK$df"
        elif [[ "$iStatus" == "301" ]]; then
            echo -e "     $wh Status$df       : $lgn$iStatus Moved Permanently$df"
        elif [[ "$iStatus" == "403" ]]; then
            newI=`curl -I $URL 2> /dev/null | sed -n 1p | awk '{print $2" "$3" "$4}'`
            echo -e "     $wh Status$df       : $lrd$newI$df"
            echo -e "   ⚠️$lyw  See README.md to fix $newI\n$df"
        else
            newI=`curl -I $URL 2> /dev/null | sed -n 1p | awk '{print $2" "$3" "$4}'`
            echo -e "     $wh Status$df       : $lrd$newI$df"
        fi
        echo -e "     $wh Server$df       : $iServer"
        echo -e "     $wh Content-Type$df : $iContent"
        echo -e "   }\n"

    }

    if [[ "$1" == "index" ]]; then

        index

    elif [[ "$1" == "myAdmin" ]]; then

        myAdmin

    fi

}

banner
status index
status myAdmin
